Using TensorFlow backend.
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcublas.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcudnn.so.5 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcufft.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcurand.so.8.0 locally
Tensorflow_lim5000_proper_split_reweight_loss_batchC.py:101: RuntimeWarning: invalid value encountered in less
  a,b,c = (data1[i][2] < 8)*1,(data1[i][2] <= 15) & (data1[i][2] >= 8)*1,(data1[i][2] > 15)*1
Tensorflow_lim5000_proper_split_reweight_loss_batchC.py:101: RuntimeWarning: invalid value encountered in less_equal
  a,b,c = (data1[i][2] < 8)*1,(data1[i][2] <= 15) & (data1[i][2] >= 8)*1,(data1[i][2] > 15)*1
Tensorflow_lim5000_proper_split_reweight_loss_batchC.py:101: RuntimeWarning: invalid value encountered in greater_equal
  a,b,c = (data1[i][2] < 8)*1,(data1[i][2] <= 15) & (data1[i][2] >= 8)*1,(data1[i][2] > 15)*1
Tensorflow_lim5000_proper_split_reweight_loss_batchC.py:101: RuntimeWarning: invalid value encountered in greater
  a,b,c = (data1[i][2] < 8)*1,(data1[i][2] <= 15) & (data1[i][2] >= 8)*1,(data1[i][2] > 15)*1
Tensorflow_lim5000_proper_split_reweight_loss_batchC.py:131: RuntimeWarning: invalid value encountered in less
  a,b,c = (data1[i][2] < 8)*1,(data1[i][2] <= 15) & (data1[i][2] >= 8)*1,(data1[i][2] > 15)*1
Tensorflow_lim5000_proper_split_reweight_loss_batchC.py:131: RuntimeWarning: invalid value encountered in less_equal
  a,b,c = (data1[i][2] < 8)*1,(data1[i][2] <= 15) & (data1[i][2] >= 8)*1,(data1[i][2] > 15)*1
Tensorflow_lim5000_proper_split_reweight_loss_batchC.py:131: RuntimeWarning: invalid value encountered in greater_equal
  a,b,c = (data1[i][2] < 8)*1,(data1[i][2] <= 15) & (data1[i][2] >= 8)*1,(data1[i][2] > 15)*1
Tensorflow_lim5000_proper_split_reweight_loss_batchC.py:131: RuntimeWarning: invalid value encountered in greater
  a,b,c = (data1[i][2] < 8)*1,(data1[i][2] <= 15) & (data1[i][2] >= 8)*1,(data1[i][2] > 15)*1
Tensorflow_lim5000_proper_split_reweight_loss_batchC.py:149: RuntimeWarning: invalid value encountered in less
  a,b,c = (data1_t[i][2] < 8)*1,(data1_t[i][2] <= 15) & (data1_t[i][2] >= 8)*1,(data1_t[i][2] > 15)*1
Tensorflow_lim5000_proper_split_reweight_loss_batchC.py:149: RuntimeWarning: invalid value encountered in less_equal
  a,b,c = (data1_t[i][2] < 8)*1,(data1_t[i][2] <= 15) & (data1_t[i][2] >= 8)*1,(data1_t[i][2] > 15)*1
Tensorflow_lim5000_proper_split_reweight_loss_batchC.py:149: RuntimeWarning: invalid value encountered in greater_equal
  a,b,c = (data1_t[i][2] < 8)*1,(data1_t[i][2] <= 15) & (data1_t[i][2] >= 8)*1,(data1_t[i][2] > 15)*1
Tensorflow_lim5000_proper_split_reweight_loss_batchC.py:149: RuntimeWarning: invalid value encountered in greater
  a,b,c = (data1_t[i][2] < 8)*1,(data1_t[i][2] <= 15) & (data1_t[i][2] >= 8)*1,(data1_t[i][2] > 15)*1
I tensorflow/core/common_runtime/gpu/gpu_device.cc:885] Found device 0 with properties: 
name: Tesla K40t
major: 3 minor: 5 memoryClockRate (GHz) 0.8755
pciBusID 0000:82:00.0
Total memory: 11.17GiB
Free memory: 11.10GiB
I tensorflow/core/common_runtime/gpu/gpu_device.cc:906] DMA: 0 
I tensorflow/core/common_runtime/gpu/gpu_device.cc:916] 0:   Y 
I tensorflow/core/common_runtime/gpu/gpu_device.cc:975] Creating TensorFlow device (/gpu:0) -> (device: 0, name: Tesla K40t, pci bus id: 0000:82:00.0)
Traceback (most recent call last):
  File "Tensorflow_lim5000_proper_split_reweight_loss_batchC.py", line 606, in <module>
    train_acc += [accuracy(np.argmax(pred[num:num+1],3)[0],np.argmax(batch_y[num:num+1],3)[0]),]
IndexError: index 0 is out of bounds for axis 0 with size 0
